#Requires -RunAsAdministrator
<#
*************************************************************************************************************************************
Name:               Create-AppLockerEvtSubscription
Author:             Kasper Johansen
Website:            https://virtualwarlock.net
Version             1.0
Last modified Date: 19-05-2020

*************************************************************************************************************************************

.SYNOPSIS
    Creates a Windows Event Log forwarding subscription.

.DESCRIPTION
    Windows Event Log forwarding subscript specifically for AppLocker events. The subscription is a source based subscription
    and collectects all events generated by AppLocker. The script relies on an XML file which holds the subscription configuration.
    This script should be executed on the server you wish to be an Event Collector Server. All collected events goes to the 
    Forwarded Events log in the Event Viewer.

#************************************************************************************************************************************
#>

# Configure Windows Event Collector Service
clear
Write-Host "Configuring Windows Event Collector service" -ForegroundColor Cyan
wecutil qc /q:TRUE

    # Create AppLocker Event Log Source Subscription
    Write-Host "Creating Windows Event Collector service subscription" -ForegroundColor Cyan
    wecutil cs ".\AppLocker.xml"

    # Configure event log subsription format
    Write-Host "Change subscription format to Events " -ForegroundColor Cyan
    wecutil ss AppLocker /cf:events

        # Change WinRM permissions based on the recommendations from Microsoft - https://support.microsoft.com/en-us/help/4494462/events-not-forwarded-if-the-collector-runs-windows-server
        $TotalMemory = Get-WmiObject Win32_OperatingSystem | Measure-Object -Property TotalVisibleMemorySize -Sum | % {[Math]::Round($_.sum/1024/1024)}
        If ($TotalMemory -ige "4")
        {
            Write-Host "Modifying WinRM permissions" -ForegroundColor Cyan
            # Remove current  WSMAN URL reservations
            Write-Host "Removing current WSMAN URL reservations" -ForegroundColor Cyan
            Start-Process -Wait "netsh.exe" -ArgumentList "http delete urlacl url=http://+:5985/wsman/"
            Start-Process -Wait "netsh.exe" -ArgumentList "http delete urlacl url=https://+:5986/wsman/"

                # Add new WSMAN URL reservations with correct permissions
                Write-Host "Adding new WSMAN URL reservations with correct permissions" -ForegroundColor Cyan
                Start-Process -Wait "netsh.exe" -ArgumentList "http add urlacl url=http://+:5985/wsman/ sddl=D:(A;;GX;;;S-1-5-80-569256582-2953403351-2909559716-1301513147-412116970)(A;;GX;;;S-1-5-80-4059739203-877974739-1245631912-527174227-2996563517)" -NoNewWindow
                Start-Process -Wait "netsh.exe" -ArgumentList "http add urlacl url=https://+:5986/wsman/ sddl=D:(A;;GX;;;S-1-5-80-569256582-2953403351-2909559716-1301513147-412116970)(A;;GX;;;S-1-5-80-4059739203-877974739-1245631912-527174227-2996563517)" -NoNewWindow
        }
            # Configure the maximum log size of the Forwarded Events log to 500MB
            Write-Host "Configuring Forwarded Events Log size to 500MB" -ForegroundColor Cyan
            wevtutil set-Log "ForwardedEvents" /ms:512000000

            # Restart Windows Remote Management and Windows Event Collector services
            Restart-Service -Name WinRM
            Restart-Service -Name Wecsvc